Internal Server Error: /api/v1/alldistrict
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/tnemis/views.py", line 19, in district_list
    schooldist = SchoolDistrict.get_districts()
TypeError: get_districts() missing 1 required positional argument: 'cls'
"GET /api/v1/alldistrict HTTP/1.1" 500 90141
Internal Server Error: /api/v1/alldistrict
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/tnemis/views.py", line 19, in district_list
    schooldist = SchoolDistrict.get_districts()
TypeError: get_districts() missing 1 required positional argument: 'cls'
"GET /api/v1/alldistrict HTTP/1.1" 500 90141
Internal Server Error: /api/v1/alldistrict
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/tnemis/views.py", line 19, in district_list
    schooldist = SchoolDistrict.get_districts()
TypeError: get_districts() missing 1 required positional argument: 'self'
"GET /api/v1/alldistrict HTTP/1.1" 500 90147
Internal Server Error: /api/v1/alldistrict
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/tnemis/views.py", line 19, in district_list
    schooldist = SchoolDistrict.get_districts()
TypeError: get_districts() missing 1 required positional argument: 'self'
"GET /api/v1/alldistrict HTTP/1.1" 500 90147
Internal Server Error: /api/v1/alldistrict
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/tnemis/views.py", line 19, in district_list
    schooldist = SchoolDistrict.get_districts()
TypeError: get_districts() missing 1 required positional argument: 'self'
"GET /api/v1/alldistrict HTTP/1.1" 500 90147
Internal Server Error: /api/v1/alldistrict
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/tnemis/views.py", line 19, in district_list
    schooldist = SchoolDistrict.get_districts()
TypeError: get_districts() missing 1 required positional argument: 'self'
"GET /api/v1/alldistrict HTTP/1.1" 500 90147
Internal Server Error: /api/v1/alldistrict
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/tnemis/views.py", line 19, in district_list
    schooldist = SchoolDistrict.get_districts()
TypeError: get_districts() missing 1 required positional argument: 'self'
"GET /api/v1/alldistrict HTTP/1.1" 500 90147
Internal Server Error: /api/v1/alldistrict
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/tnemis/views.py", line 19, in district_list
    schooldist = SchoolDistrict.get_districts()
TypeError: get_districts() missing 1 required positional argument: 'self'
"GET /api/v1/alldistrict HTTP/1.1" 500 90147
Internal Server Error: /api/v1/alldistrict
Traceback (most recent call last):
  File "/app/tnemis/models.py", line 13, in get_districts
    return self.objects.using(using).all()
  File "/py/lib/python3.9/site-packages/django/db/models/manager.py", line 179, in __get__
    raise AttributeError("Manager isn't accessible via %s instances" % cls.__name__)
AttributeError: Manager isn't accessible via SchoolDistrict instances

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/tnemis/views.py", line 19, in district_list
    schooldist = SchoolDistrict().get_districts()
  File "/app/tnemis/models.py", line 16, in get_districts
    return self.objects.none()
  File "/py/lib/python3.9/site-packages/django/db/models/manager.py", line 179, in __get__
    raise AttributeError("Manager isn't accessible via %s instances" % cls.__name__)
AttributeError: Manager isn't accessible via SchoolDistrict instances
"GET /api/v1/alldistrict HTTP/1.1" 500 104790
Internal Server Error: /api/v1/alldistrict
Traceback (most recent call last):
  File "/app/tnemis/models.py", line 13, in get_districts
    return self.objects.using(using).all()
  File "/py/lib/python3.9/site-packages/django/db/models/manager.py", line 179, in __get__
    raise AttributeError("Manager isn't accessible via %s instances" % cls.__name__)
AttributeError: Manager isn't accessible via SchoolDistrict instances

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/tnemis/views.py", line 19, in district_list
    schooldist = SchoolDistrict().get_districts()
  File "/app/tnemis/models.py", line 16, in get_districts
    return self.objects.none()
  File "/py/lib/python3.9/site-packages/django/db/models/manager.py", line 179, in __get__
    raise AttributeError("Manager isn't accessible via %s instances" % cls.__name__)
AttributeError: Manager isn't accessible via SchoolDistrict instances
"GET /api/v1/alldistrict HTTP/1.1" 500 104790
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=10011301 HTTP/1.1" 500 81829
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=1 HTTP/1.1" 500 81745
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=1 HTTP/1.1" 500 81745
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=1 HTTP/1.1" 500 81745
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=1 HTTP/1.1" 500 81745
Internal Server Error: /api/v1/Tchrdet
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
TypeError: Tchrdet() takes 1 positional argument but 2 were given
"GET /api/v1/Tchrdet?TchrId=1 HTTP/1.1" 500 81745
"POST /api/v1/CnslMainPage HTTP/1.1" 500 59
"POST /api/v1/CnslMainPage HTTP/1.1" 500 59
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 92
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 115
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 115
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 115
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 104
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 111
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 128
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 128
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 128
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 128
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 55
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 104
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 55
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 55
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 128
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 124
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 124
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 124
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 124
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 124
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 124
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 124
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 55
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 104
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 55
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 55
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 55
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 109
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 55
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 55
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 128
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 279
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 81
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 109
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 110
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 110
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 110
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 108
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 53
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 128
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 54
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 128
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 128
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 128
Internal Server Error: /api/v1/CnslMainPage
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
"POST /api/v1/CnslMainPage HTTP/1.1" 500 72775
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 128
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 124
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 124
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 124
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 124
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 124
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 53
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 55
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 128
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 128
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 128
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 128
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 128
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 128
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 128
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 127
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 136
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 59
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 59
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 59
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 109
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 59
Internal Server Error: /api/v1/login
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
"POST /api/v1/login HTTP/1.1" 500 72598
Internal Server Error: /api/v1/login
Traceback (most recent call last):
  File "/py/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/py/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/py/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/py/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
"POST /api/v1/login HTTP/1.1" 500 72598
An error occurred: die
An error occurred: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")
An error occurred: die
An error occurred: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")
An error occurred: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")
An error occurred: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")
An error occurred: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")
An error occurred: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")
An error occurred: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")
An error occurred: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1")
An error occurred: die
An error occurred: die
An error occurred: die
An error occurred: die
An error occurred: die
An error occurred: die
An error occurred: die
An error occurred: (1290, 'The MySQL server is running with the --read-only option so it cannot execute this statement')
Internal Server Error: /api/v1/CnslMainPage
"POST /api/v1/CnslMainPage HTTP/1.1" 500 152
